<?php
$e = 'home_next_escape';
$copy = $homeNextCopy;
$facilitiesPath = site_localized_path('/co-so-y-te', $locale);
$doctorsPath = site_localized_path('/bac-si', $locale);
$toplistsPath = site_localized_path('/toplist', $locale);
$homeNextNumber = static fn(int $value): string => number_format($value, 0, $locale === 'en' ? '.' : ',', $locale === 'en' ? ',' : '.');
?>
<div class="hn-preview"><div class="hn-wrap"><span><span aria-hidden="true"></span><?= $e($copy['preview']) ?></span><a href="<?= $e(site_localized_path('/', $locale)) ?>"><?= $e($copy['old']) ?><i class="ph ph-arrow-up-right" aria-hidden="true"></i></a></div></div>
<main class="med-home hc-home hn-home" id="main" data-locale="<?= $e($locale) ?>">
  <section class="hn-hero hn-wrap" aria-labelledby="hn-title">
    <div class="hn-hero-copy"><p class="hn-eyebrow"><span aria-hidden="true"></span><?= $e($copy['eyebrow']) ?></p><h1 id="hn-title"><?= $e($copy['title']) ?><br><em><?= $e($copy['accent']) ?></em></h1><p class="hn-hero-description"><?= $e($copy['heroCopy']) ?></p><a class="hn-hero-link" href="#hn-explore"><?= $e($copy['seeMore']) ?><i class="ph ph-arrow-down" aria-hidden="true"></i></a></div>
    <div class="hn-visual"><span class="hn-visual-orbit" aria-hidden="true"></span><figure class="hn-photo"><img src="<?= $e($heroImage) ?>" alt="<?= $e($copy['photoAlt']) ?>" width="1800" height="720" fetchpriority="high" decoding="async"><figcaption><i class="ph ph-heart" aria-hidden="true"></i><?= $e($copy['photoLabel']) ?><small><?= $e($copy['illustration']) ?></small></figcaption></figure><span class="hn-float-cross" aria-hidden="true"><i class="ph ph-first-aid"></i></span><div class="hn-float-note"><i class="ph ph-shield-check" aria-hidden="true"></i><span><strong><?= $e($copy['noteTitle']) ?></strong><small><?= $e($copy['noteMeta']) ?></small></span></div></div>
  </section>
  <section class="hn-find hn-wrap" aria-labelledby="hn-search-label">
    <div class="hn-find-top"><h2 id="hn-search-label"><?= $e($copy['search']) ?></h2><span><i class="ph ph-sparkle" aria-hidden="true"></i>MedReview</span></div>
    <div class="medical-search-shell hero-search-shell search-panel hn-search" data-medical-search>
      <form action="<?= $e($facilitiesPath) ?>" method="get" role="search" aria-label="<?= $e($copy['search']) ?>"><label class="search-field" for="hn-search-input"><i class="ph ph-magnifying-glass" aria-hidden="true"></i><span class="hn-sr-only"><?= $e($copy['search']) ?></span><input id="hn-search-input" type="search" name="q" maxlength="120" data-medical-search-input placeholder="<?= $e($copy['placeholder']) ?>" autocomplete="off" enterkeyhint="search"></label><button type="button" class="send-button" aria-label="<?= $e($copy['searchButton']) ?>"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m21 3-6.8 18-3.5-7.7L3 9.8 21 3Z"/><path d="m10.7 13.3 5.5-5.5"/></svg></button></form>
      <div class="medical-search-results" data-medical-search-results hidden></div>
    </div>
    <div class="hn-quick"><span><?= $e($copy['try']) ?></span><?php foreach ($copy['terms'] as $term): ?><button type="button" data-home-query="<?= $e($term) ?>"><?= $e($term) ?><i class="ph ph-arrow-up-left" aria-hidden="true"></i></button><?php endforeach; ?></div>
  </section>
  <div class="hn-proof hn-wrap"><span><i class="ph ph-hospital" aria-hidden="true"></i><strong><?= $homeNextNumber((int) $homeNextData['stats']['facilities']) ?></strong><?= $e($copy['facilitiesStat']) ?></span><span><i class="ph ph-stethoscope" aria-hidden="true"></i><strong><?= $homeNextNumber((int) $homeNextData['stats']['doctors']) ?></strong><?= $e($copy['doctorsStat']) ?></span><span><i class="ph ph-stack" aria-hidden="true"></i><?= $e($copy['sources']) ?></span></div>
  <section class="hn-specialties hn-wrap" id="hn-explore" aria-labelledby="hn-specialties-title"><div class="hn-heading is-compact"><h2 id="hn-specialties-title"><?= $e($copy['specialties']) ?></h2><a class="hn-text-link" href="<?= $e($facilitiesPath) ?>"><?= $e($copy['seeMore']) ?><i class="ph ph-arrow-right" aria-hidden="true"></i></a></div><div class="hn-specialty-grid"><?php foreach ($copy['specialtyItems'] as [$name,$description,$query,$icon]): ?><a class="hn-specialty" href="<?= $e($facilitiesPath . '?' . http_build_query(['q'=>$query])) ?>"><span class="hn-specialty-icon"><i class="ph ph-<?= $icon ?>" aria-hidden="true"></i></span><strong><?= $e($name) ?></strong><small><?= $e($description) ?></small></a><?php endforeach; ?></div></section>
  <section class="hn-section hn-facilities" aria-labelledby="hn-facilities-title"><div class="hn-wrap"><div class="hn-heading hn-reveal"><div><p class="hn-eyebrow"><?= $e($copy['facilityKicker']) ?></p><h2 id="hn-facilities-title"><?= $e($copy['facilityTitle']) ?></h2><p><?= $e($copy['facilityCopy']) ?></p></div><a class="hn-text-link" href="<?= $e($facilitiesPath) ?>"><?= $e($copy['allFacilities']) ?><i class="ph ph-arrow-up-right" aria-hidden="true"></i></a></div><div class="hn-city-filters" role="group" aria-label="<?= $locale === 'en' ? 'Filter featured facilities by city' : 'Lọc cơ sở nổi bật theo thành phố' ?>"><?php foreach (['all'=>$copy['all'],'hcm'=>'TP. Hồ Chí Minh','hanoi'=>'Hà Nội','danang'=>'Đà Nẵng'] as $region=>$name): ?><button type="button" data-home-next-city="<?= $region ?>" aria-pressed="<?= $region === 'all' ? 'true' : 'false' ?>"><?= $e($name) ?></button><?php endforeach; ?></div>
    <div class="hn-facility-grid" data-home-next-facilities>
      <?php foreach ($homeNextData['facilities'] as $index=>$facility): $url=medical_public_entity_path('facility',(string)$facility['slug'],$locale); $image=(string)($facility['image_url']??''); ?>
      <article class="hn-facility hn-reveal" data-region="<?= home_next_region((string)$facility['city']) ?>" data-facility-id="<?= (int)$facility['id'] ?>"<?= $index >= 3 ? ' hidden' : '' ?>><div class="hn-facility-media"><a href="<?= $e($url) ?>" aria-label="<?= $e($facility['name']) ?>"><span class="hn-image-fallback" aria-hidden="true"><i class="ph ph-hospital"></i></span><?php if ($image !== ''): ?><img src="<?= $e($image) ?>" alt="" width="640" height="420" loading="lazy" decoding="async" data-hn-image><?php endif; ?></a><span class="hn-category"><?= $e($facility['category']) ?></span><button class="hn-save" type="button" aria-pressed="false" aria-label="<?= $e($copy['save'].' · '.$facility['name']) ?>"><i class="ph ph-bookmark-simple" aria-hidden="true"></i></button></div><div class="hn-facility-body"><h3><a href="<?= $e($url) ?>"><?= $e($facility['name']) ?></a><?php if ((int)$facility['verified'] === 1): ?><a class="hn-verified facility-verification-link facility-verification-icon" href="<?= $e(site_localized_path('/ho-so-da-xac-thuc', $locale)) ?>" aria-label="<?= $locale === 'en' ? 'Understand the verified facility profile label' : 'Tìm hiểu hồ sơ cơ sở đã xác thực' ?>" title="<?= $locale === 'en' ? 'Verified facility profile' : 'Hồ sơ cơ sở đã xác thực' ?>"><i class="ph-fill ph-seal-check" aria-hidden="true"></i></a><?php endif; ?></h3><p class="hn-location"><i class="ph ph-map-pin" aria-hidden="true"></i><?= $e($facility['address_text'] ?: $facility['city']) ?></p><p class="hn-description"><?= $e(home_next_summary($facility['subtitle']??'',$copy['fallback'])) ?></p><div class="hn-card-footer"><span class="hn-rating"><?php if ((int)$facility['reviews_count']>0 && (float)$facility['rating']>0): ?><i class="ph-fill ph-star" aria-hidden="true"></i><strong><?= number_format((float)$facility['rating'],1) ?></strong><small>(<?= $homeNextNumber((int)$facility['reviews_count']) ?> <?= $e($copy['reviews']) ?>)</small><?php else: ?><small><?= $e($copy['noRating']) ?></small><?php endif; ?></span><a href="<?= $e($url) ?>"><?= $e($copy['profile']) ?><i class="ph ph-arrow-right" aria-hidden="true"></i></a></div></div></article>
      <?php endforeach; ?>
      <p class="hn-empty" data-home-next-empty<?= $homeNextData['facilities'] !== [] ? ' hidden' : '' ?>><?= $e($copy['facilityEmpty']) ?> <a href="<?= $e($facilitiesPath) ?>"><?= $e($copy['allFacilities']) ?> →</a></p>
    </div>
  </div></section>
  <section class="hn-section hn-doctors hn-wrap" aria-labelledby="hn-doctors-title"><div class="hn-heading hn-reveal"><div><p class="hn-eyebrow"><?= $e($copy['doctorKicker']) ?></p><h2 id="hn-doctors-title"><?= $e($copy['doctorTitle']) ?></h2><p><?= $e($copy['doctorCopy']) ?></p></div><a class="hn-text-link" href="<?= $e($doctorsPath) ?>"><?= $e($copy['allDoctors']) ?><i class="ph ph-arrow-up-right" aria-hidden="true"></i></a></div><div class="hn-doctor-grid"><?php foreach ($homeNextData['doctors'] as $doctor): $url=medical_public_entity_path('doctor',(string)$doctor['slug'],$locale); ?><article class="hn-doctor hn-reveal"><a class="hn-doctor-photo" href="<?= $e($url) ?>" aria-label="<?= $e($doctor['name']) ?>"><span class="hn-image-fallback" aria-hidden="true"><i class="ph ph-user-circle"></i></span><?php if (trim((string)($doctor['image_url']??'')) !== ''): ?><img src="<?= $e($doctor['image_url']) ?>" alt="" width="240" height="280" loading="lazy" decoding="async" data-hn-image><?php endif; ?></a><div><p class="hn-doctor-specialty"><?= $e($doctor['specialty_text']) ?></p><h3><a href="<?= $e($url) ?>"><?= $e($doctor['name']) ?></a></h3><p class="hn-doctor-meta"><?= $e(home_next_summary($doctor['title_text']??'',$copy['doctorFallback'],80)) ?></p><span class="hn-doctor-city"><i class="ph ph-map-pin" aria-hidden="true"></i><?= $e($doctor['city']) ?></span><a class="hn-text-link" href="<?= $e($url) ?>"><?= $e($copy['profile']) ?><i class="ph ph-arrow-right" aria-hidden="true"></i></a></div></article><?php endforeach; ?><?php if ($homeNextData['doctors'] === []): ?><a class="hn-directory-invite" href="<?= $e($doctorsPath) ?>"><i class="ph ph-stethoscope" aria-hidden="true"></i><span><?= $e($copy['doctorFallback']) ?></span><i class="ph ph-arrow-up-right" aria-hidden="true"></i></a><?php endif; ?></div></section>
  <section class="hn-section hn-toplists" aria-labelledby="hn-toplists-title"><div class="hn-wrap"><div class="hn-heading hn-reveal"><div><p class="hn-eyebrow"><?= $e($copy['toplistKicker']) ?></p><h2 id="hn-toplists-title"><?= $e($copy['toplistTitle']) ?></h2><p><?= $e($copy['toplistCopy']) ?></p></div><a class="hn-text-link" href="<?= $e($toplistsPath) ?>"><?= $e($copy['allToplists']) ?><i class="ph ph-arrow-up-right" aria-hidden="true"></i></a></div><div class="hn-toplist-grid"><?php foreach ($homeNextData['toplists'] as $index=>$toplist): $url=medical_public_entity_path('toplist',(string)$toplist['slug'],$locale); ?><article class="hn-toplist hn-reveal"><div class="hn-toplist-top"><span>MEDREVIEW · TOPLIST</span><i class="ph ph-stack" aria-hidden="true"></i></div><span class="hn-toplist-number" aria-hidden="true"><?= str_pad((string)($index+1),2,'0',STR_PAD_LEFT) ?></span><h3><a href="<?= $e($url) ?>"><?= $e($toplist['title']) ?></a></h3><p><?= $e(home_next_summary($toplist['excerpt']??'',$copy['listFallback'],125)) ?></p><div class="hn-toplist-footer"><span><?= $homeNextNumber((int)$toplist['member_count']) ?> <?= $e($copy['profiles']) ?></span><a href="<?= $e($url) ?>" aria-label="<?= $e($copy['listCta'].' · '.$toplist['title']) ?>"><i class="ph ph-arrow-up-right" aria-hidden="true"></i></a></div></article><?php endforeach; ?><?php if ($homeNextData['toplists'] === []): ?><a class="hn-directory-invite" href="<?= $e($toplistsPath) ?>"><i class="ph ph-stack" aria-hidden="true"></i><span><?= $e($copy['toplistCopy']) ?></span><i class="ph ph-arrow-up-right" aria-hidden="true"></i></a><?php endif; ?></div></div></section>
  <section class="hn-process hn-wrap hn-reveal" aria-labelledby="hn-process-title"><h2 id="hn-process-title"><?= $e($copy['stepsTitle']) ?></h2><div class="hn-step-grid"><?php foreach ($copy['steps'] as $index=>[$icon,$title,$description]): ?><article><span class="hn-step-icon"><i class="ph ph-<?= $icon ?>" aria-hidden="true"></i><small><?= $index+1 ?></small></span><div><h3><?= $e($title) ?></h3><p><?= $e($description) ?></p></div></article><?php endforeach; ?></div></section>
  <section class="hn-community hn-wrap hn-reveal" aria-labelledby="hn-community-title"><div class="hn-community-copy"><p class="hn-eyebrow"><?= $e($copy['communityKicker']) ?></p><h2 id="hn-community-title"><?= $e($copy['communityTitle']) ?></h2><p><?= $e($copy['communityCopy']) ?></p><a class="hn-button" href="<?= $e(site_localized_path('/review.php',$locale)) ?>"><?= $e($copy['communityCta']) ?><i class="ph ph-arrow-right" aria-hidden="true"></i></a></div><div class="hn-community-art"><span class="hn-community-sticker" aria-hidden="true"><i class="ph ph-chat-circle-text"></i></span><div class="hn-question"><i class="ph ph-quotes" aria-hidden="true"></i><p><?= $e($copy['communityQuestion']) ?></p><div><?php foreach ($copy['communityChips'] as $chip): ?><span><?= $e($chip) ?></span><?php endforeach; ?></div><small><?= $e($copy['communityFoot']) ?></small></div><span class="hn-community-heart" aria-hidden="true"><i class="ph-fill ph-heart"></i></span></div></section>
  <p class="hn-disclaimer hn-wrap"><i class="ph ph-info" aria-hidden="true"></i><?= $e($copy['disclaimer']) ?></p>
</main>
