<?php
declare(strict_types=1);
require_once __DIR__ . '/_bootstrap.php';
admin_require_login();
$adminPageTitle = 'Admin • Thư viện';
$adminHeaderTitle = 'Thư viện media';
$adminHeaderSubtitle = 'Quản lý folder và ảnh theo kiểu Finder';
$adminActive = 'library';
require __DIR__ . '/_layout_start.php';
?>

<style>
  .finder { --line:#e5eaf3; --blue:#2463eb; display:grid; grid-template-columns:250px minmax(0,1fr); min-height:min(720px,calc(100vh - 185px)); overflow:hidden; border:1px solid var(--line); border-radius:20px; background:#fff; box-shadow:0 18px 48px rgba(35,57,93,.08); }
  .finder-side { display:flex; flex-direction:column; min-width:0; border-right:1px solid var(--line); background:linear-gradient(180deg,#fcfdff,#f4f8ff); }
  .finder-brand { display:flex; align-items:center; gap:.65rem; padding:1.1rem 1rem .8rem; color:#182640; font-weight:800; }
  .finder-brand i { display:grid; width:2rem; height:2rem; place-items:center; border-radius:.7rem; color:#fff; background:linear-gradient(135deg,#3c7af7,#215ce2); box-shadow:0 7px 16px rgba(36,99,235,.24); }
  .finder-side-actions { display:grid; grid-template-columns:1fr 1fr; gap:.5rem; padding:0 1rem 1rem; }
  .finder-side-actions .btn,.finder-toolbar .btn { border-radius:.7rem; font-size:.81rem; font-weight:700; }
  .finder-label { padding:.2rem 1rem .45rem; color:#8997ac; font-size:.67rem; font-weight:800; letter-spacing:.08em; text-transform:uppercase; }
  .folder-tree { flex:1; min-height:180px; padding:0 .55rem 1rem; overflow:auto; }
  .tree-item { display:flex; align-items:center; width:100%; min-width:0; gap:.55rem; padding:.52rem .6rem; border:0; border-radius:.65rem; color:#47556d; background:transparent; text-align:left; font-size:.84rem; transition:.15s; }
  .tree-item:hover { color:#1f55c4; background:rgba(36,99,235,.07); }.tree-item.active { color:#1d55c9; background:#e8f0ff; font-weight:750; }
  .tree-item .name { flex:1; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }.tree-item .count { color:#91a0b8; font-size:.72rem; font-weight:700; }.tree-item .fa-folder { color:#e7a220; }
  .finder-filter { margin:.25rem 1rem 1rem; padding-top:.85rem; border-top:1px solid var(--line); }.finder-filter .form-select { border-radius:.7rem; font-size:.81rem; }
  .finder-main { display:flex; min-width:0; flex-direction:column; }.finder-toolbar { display:flex; align-items:center; gap:.7rem; min-height:73px; padding:.8rem 1rem; border-bottom:1px solid var(--line); }
  .finder-icon { display:grid; flex:0 0 auto; width:2.2rem; height:2.2rem; place-items:center; border:1px solid #dce5f2; border-radius:.65rem; color:#4a5c77; background:#fff; }.finder-icon:hover:not(:disabled){color:#1e5de1;border-color:#b7cdf8;background:#f4f8ff}.finder-icon:disabled{opacity:.4}
  .crumbs { display:flex; flex:1; align-items:center; min-width:0; gap:.32rem; overflow:auto; white-space:nowrap; }.crumb { max-width:180px; overflow:hidden; padding:.3rem .36rem; border:0; border-radius:.45rem; color:#52627b; background:transparent; font-size:.86rem; text-overflow:ellipsis; white-space:nowrap; }.crumb:hover{color:#1b5be2;background:#f1f5fc}.crumb.current{color:#1b2942;font-weight:800}.sep{color:#a5b0c1;font-size:.72rem}
  .finder-search { width:min(285px,28vw); }.finder-search .input-group-text,.finder-search .form-control { border-color:#dfe6f2; background:#fafcff; }.finder-search .input-group-text{border-radius:.7rem 0 0 .7rem;color:#7890b7}.finder-search .form-control{border-radius:0 .7rem .7rem 0;font-size:.83rem}.finder-search .form-control:focus{box-shadow:none;border-color:#8fb4ff;background:#fff}
  .finder-content { position:relative; flex:1; min-height:0; padding:1.1rem; overflow:auto; }.finder-content.dragging{outline:2px dashed #3d78ea;outline-offset:-12px;background:#f3f7ff}.content-head{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-bottom:1rem}.content-title{margin:0;color:#1a2740;font-size:1.08rem;font-weight:800}.content-meta{color:#687790;font-size:.8rem}.content-actions{display:flex;align-items:center;gap:.65rem}.drop-note{color:#7c8da7;font-size:.78rem}.content-actions .btn{border-radius:.64rem;font-size:.76rem;font-weight:750;white-space:nowrap}
  .folder-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(155px,1fr)); gap:.75rem; margin-bottom:1.2rem; }.folder-card{display:flex;align-items:center;min-width:0;gap:.7rem;padding:.78rem;border:1px solid #e0e7f3;border-radius:.9rem;color:#293852;background:#fff;text-align:left;transition:.16s}.folder-card:hover,.media-card:hover{transform:translateY(-2px);border-color:#b9cdf3;box-shadow:0 8px 18px rgba(45,79,130,.1)}.folder-card .fa-folder{color:#efae2f;font-size:1.5rem}.folder-card span{min-width:0}.folder-card strong,.folder-card small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.folder-card strong{font-size:.82rem}.folder-card small{margin-top:.15rem;color:#8b99ad;font-size:.72rem}
  .media-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(148px,1fr)); gap:.9rem; }.media-card{min-width:0;overflow:hidden;border:1px solid #e1e7f1;border-radius:.95rem;background:#fff;transition:.16s}.media-preview{position:relative;aspect-ratio:1/.78;overflow:hidden;background:#f3f6fb}.media-preview img{width:100%;height:100%;object-fit:cover;display:block}.video-preview{display:grid;width:100%;height:100%;place-items:center;color:#72829a}.media-type{position:absolute;right:.45rem;bottom:.45rem;padding:.22rem .4rem;border-radius:.45rem;color:#fff;background:rgba(18,32,56,.72);font-size:.62rem;font-weight:800}.media-info{padding:.62rem .68rem .68rem}.media-name{display:block;overflow:hidden;color:#2d3b54;font-size:.77rem;font-weight:750;text-overflow:ellipsis;white-space:nowrap}.media-detail{display:flex;justify-content:space-between;gap:.3rem;margin-top:.26rem;color:#8795aa;font-size:.67rem}
  .folder-card,.media-card{position:relative}.folder-card{cursor:pointer}.selectable.is-selected{border-color:#4d83ef!important;background:#f4f8ff;box-shadow:0 0 0 3px rgba(48,105,235,.13),0 9px 20px rgba(45,79,130,.11)}.selection-toggle{position:absolute;z-index:3;top:.45rem;left:.45rem;display:grid;width:1.5rem;height:1.5rem;place-items:center;padding:0;border:1px solid #b8c8e3;border-radius:.48rem;color:#fff;background:rgba(255,255,255,.94);box-shadow:0 2px 8px rgba(20,45,83,.12);font-size:.67rem;transition:.14s}.selection-toggle:hover{border-color:#3f78e8;background:#edf4ff;color:#2463eb}.selectable.is-selected .selection-toggle{border-color:#2463eb;background:#2463eb;color:#fff}.folder-card .selection-toggle{top:.42rem;left:.42rem}.selection-toolbar{display:flex;align-items:center;gap:.55rem;min-height:2.6rem;margin:0 0 .8rem;padding:.45rem .55rem .45rem .75rem;border:1px solid #cfe0ff;border-radius:.8rem;color:#315074;background:linear-gradient(90deg,#f4f8ff,#fff)}.selection-toolbar[hidden]{display:none}.selection-toolbar strong{color:#193a6e;font-size:.81rem}.selection-toolbar .selection-actions{display:flex;align-items:center;flex-wrap:wrap;gap:.35rem;margin-left:auto}.selection-toolbar .btn{border-radius:.58rem;font-size:.75rem;font-weight:750}.selection-marquee{position:fixed;z-index:1090;pointer-events:none;border:1px solid rgba(36,99,235,.8);border-radius:.25rem;background:rgba(58,119,239,.13);box-shadow:0 0 0 1px rgba(255,255,255,.55) inset}.finder-content.is-selecting{user-select:none}
  .finder-empty{display:grid;min-height:250px;place-items:center;padding:2rem;border:1px dashed #d9e2f0;border-radius:1rem;color:#75859e;text-align:center}.finder-empty i{display:inline-grid;width:3rem;height:3rem;place-items:center;margin-bottom:.65rem;border-radius:1rem;color:#6090ed;background:#edf4ff;font-size:1.25rem}.finder-empty strong{display:block;color:#40516b}.finder-empty p{margin:.35rem 0 0;font-size:.82rem}
  .upload-progress{position:sticky;z-index:4;bottom:.15rem;display:none;max-width:440px;margin:1.2rem auto 0;padding:.75rem .85rem;border:1px solid #d8e6ff;border-radius:.8rem;background:rgba(255,255,255,.96);box-shadow:0 10px 25px rgba(35,75,140,.13)}.upload-progress.show{display:block}
  .context-menu{position:fixed;z-index:1080;width:215px;overflow:hidden;padding:.35rem;border:1px solid #dce5f2;border-radius:.8rem;background:rgba(255,255,255,.98);box-shadow:0 16px 38px rgba(24,45,78,.18);backdrop-filter:blur(14px)}.context-menu[hidden]{display:none}.context-action{display:flex;align-items:center;width:100%;gap:.65rem;padding:.58rem .65rem;border:0;border-radius:.52rem;color:#33435d;background:transparent;text-align:left;font-size:.82rem}.context-action:hover{color:#1354d4;background:#edf4ff}.context-action.danger:hover{color:#bd2b3e;background:#fff0f2}.context-sep{height:1px;margin:.3rem;background:#edf0f5}
  .folder-dialog{width:min(420px,calc(100vw - 2rem));padding:0;border:0;border-radius:1rem;box-shadow:0 24px 70px rgba(20,37,68,.25)}.folder-dialog::backdrop{background:rgba(18,30,52,.28);backdrop-filter:blur(2px)}.dialog-inner{padding:1.25rem}.dialog-inner h2{margin:0;color:#25334a;font-size:1.08rem;font-weight:800}.dialog-inner p{margin:.3rem 0 1rem;color:#78879c;font-size:.83rem}.dialog-inner .form-control{border-radius:.7rem}.dialog-actions{display:flex;justify-content:flex-end;gap:.55rem;margin-top:1rem}.dialog-actions .btn{border-radius:.68rem;font-weight:700}
  @media(max-width:991.98px){.finder{grid-template-columns:215px minmax(0,1fr)}.finder-search{width:205px}}
  @media(max-width:767.98px){.finder{display:block;min-height:0;overflow:visible}.finder-side{border-right:0;border-bottom:1px solid var(--line)}.folder-tree{display:flex;max-height:126px;min-height:0;gap:.3rem;padding:0 .8rem .7rem;overflow-x:auto;overflow-y:hidden}.tree-item{flex:0 0 auto;width:auto}.tree-item[style*="padding-left"]{padding-left:.6rem!important}.tree-item .count{display:none}.finder-filter{display:none}.finder-toolbar{flex-wrap:wrap}.crumbs{order:3;flex-basis:100%;width:100%}.finder-search{flex:1;width:auto}.finder-content{padding:.8rem}.content-head{align-items:flex-start;flex-direction:column;gap:.25rem}.folder-grid,.media-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:.6rem}.drop-note{display:none}.selection-toolbar{align-items:flex-start;flex-direction:column}.selection-toolbar .selection-actions{width:100%;margin-left:0}.selection-toolbar .btn{flex:1}.selection-toggle{width:1.65rem;height:1.65rem}}
</style>

<div class="finder" id="finder">
  <aside class="finder-side" id="finderSide">
    <div class="finder-brand"><i class="fa-solid fa-photo-film" aria-hidden="true"></i><span>Thư viện media</span></div>
    <div class="finder-side-actions"><button id="btnUpload" class="btn btn-primary" type="button"><i class="fa-solid fa-arrow-up-from-bracket me-1"></i>Upload</button><button id="btnNewFolder" class="btn btn-outline-primary" type="button"><i class="fa-solid fa-folder-plus me-1"></i>Folder</button><input id="uploadInput" type="file" accept="image/*,video/mp4" multiple hidden></div>
    <div class="finder-label">Vị trí</div><div id="folderTree" class="folder-tree" aria-label="Cây thư mục"></div>
    <div class="finder-filter"><label for="typeFilter" class="form-label small fw-semibold text-secondary mb-1">Hiển thị</label><select id="typeFilter" class="form-select"><option value="all">Tất cả file</option><option value="image">Chỉ ảnh</option><option value="video">Chỉ MP4</option></select></div>
  </aside>
  <section class="finder-main">
    <div class="finder-toolbar"><button id="btnBack" class="finder-icon" type="button" title="Quay lại" disabled><i class="fa-solid fa-arrow-left"></i></button><button id="btnUp" class="finder-icon" type="button" title="Folder cha" disabled><i class="fa-solid fa-arrow-up"></i></button><nav id="breadcrumbs" class="crumbs" aria-label="Đường dẫn folder"></nav><div class="finder-search input-group"><span class="input-group-text"><i class="fa-solid fa-magnifying-glass"></i></span><input id="searchInput" class="form-control" placeholder="Tìm ảnh, folder..." autocomplete="off"></div><button id="btnReload" class="finder-icon" type="button" title="Reload"><i class="fa-solid fa-rotate"></i></button></div>
    <div id="finderContent" class="finder-content" tabindex="0"><div class="content-head"><div><h1 id="viewTitle" class="content-title">Tất cả folder</h1><div id="meta" class="content-meta">Đang tải thư viện...</div></div><div class="content-actions"><div class="drop-note"><i class="fa-solid fa-cloud-arrow-up me-1"></i>Kéo thả ảnh vào đây để upload</div><button id="btnSelectAllQuick" class="btn btn-outline-primary" type="button"><i class="fa-solid fa-check-double me-1"></i>Chọn tất cả</button></div></div><div id="selectionToolbar" class="selection-toolbar" hidden><strong id="selectionCount">0 mục đã chọn</strong><span class="small text-secondary">Kéo vùng trống để khoanh chọn · Ctrl/Cmd-click để chọn thêm</span><div class="selection-actions"><button id="btnSelectAll" class="btn btn-light" type="button"><i class="fa-solid fa-check-double me-1"></i>Chọn tất cả đang hiển thị</button><button id="btnClearSelection" class="btn btn-light" type="button"><i class="fa-solid fa-xmark me-1"></i>Bỏ chọn</button><button id="btnDeleteSelected" class="btn btn-outline-danger" type="button"><i class="fa-solid fa-trash-can me-1"></i>Xoá đã chọn</button></div></div><div id="folderGrid" class="folder-grid"></div><div id="mediaGrid" class="media-grid"></div><div id="empty" class="finder-empty d-none"><div><i class="fa-regular fa-folder-open"></i><strong>Folder này chưa có file</strong><p>Click chuột phải để tạo folder mới hoặc kéo ảnh vào đây.</p></div></div><div id="uploadProgress" class="upload-progress" role="status"><div class="d-flex justify-content-between gap-2 small mb-2"><span id="uploadProgressLabel" class="text-secondary">Đang tải lên...</span><strong id="uploadProgressText">0%</strong></div><div class="progress" style="height:.5rem"><div id="uploadProgressBar" class="progress-bar progress-bar-striped progress-bar-animated" style="width:0%"></div></div></div></div>
  </section>
</div>

<div id="contextMenu" class="context-menu" hidden role="menu"></div>
<div id="selectionMarquee" class="selection-marquee" hidden aria-hidden="true"></div>
<dialog id="folderDialog" class="folder-dialog"><form id="folderCreateForm" class="dialog-inner"><h2>Tạo folder mới</h2><p id="folderDialogPath">Trong Thư viện</p><label for="folderNameInput" class="form-label small fw-semibold">Tên folder</label><input id="folderNameInput" class="form-control" maxlength="80" placeholder="Ví dụ: ảnh phòng khám" autocomplete="off" required><div class="dialog-actions"><button id="btnCancelFolder" class="btn btn-light" type="button">Huỷ</button><button class="btn btn-primary" type="submit"><i class="fa-solid fa-folder-plus me-1"></i>Tạo folder</button></div></form></dialog>

<script>
  const ALL = "__all__";
  const $ = (id) => document.getElementById(id);
  const el = { uploadInput:$("uploadInput"), btnUpload:$("btnUpload"), btnNewFolder:$("btnNewFolder"), btnReload:$("btnReload"), btnBack:$("btnBack"), btnUp:$("btnUp"), content:$("finderContent"), tree:$("folderTree"), folders:$("folderGrid"), grid:$("mediaGrid"), crumbs:$("breadcrumbs"), type:$("typeFilter"), search:$("searchInput"), meta:$("meta"), title:$("viewTitle"), empty:$("empty"), menu:$("contextMenu"), dialog:$("folderDialog"), form:$("folderCreateForm"), folderName:$("folderNameInput"), dialogPath:$("folderDialogPath"), cancelFolder:$("btnCancelFolder"), progress:$("uploadProgress"), progressBar:$("uploadProgressBar"), progressText:$("uploadProgressText"), progressLabel:$("uploadProgressLabel"), selectionToolbar:$("selectionToolbar"), selectionCount:$("selectionCount"), btnSelectAll:$("btnSelectAll"), btnSelectAllQuick:$("btnSelectAllQuick"), btnClearSelection:$("btnClearSelection"), btnDeleteSelected:$("btnDeleteSelected"), marquee:$("selectionMarquee") };
  let files = [], folders = [], totalFiles = 0, folderTotalFiles = 0, folderFileCounts = {}, active = ALL, history = [ALL], historyIndex = 0, dialogParent = "", contextTarget = null, selectedFiles = new Set(), selectedFolders = new Set(), selectionMode = false, loadSequence = 0, lasso = null, suppressCardClick = false;

  const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const bytes = (value) => { const n=Number(value||0); return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`; };
  const date = (value) => value ? new Date(Number(value)*1000).toLocaleDateString("vi-VN",{day:"2-digit",month:"2-digit",year:"numeric"}) : "";
  const norm = (value) => String(value||"").replace(/^\/+|\/+$/g,"");
  const allView = (value=active) => value === ALL;
  const parent = (folder) => { const value=norm(folder), i=value.lastIndexOf("/"); return i<0?"":value.slice(0,i); };
  const leaf = (folder) => { const value=norm(folder); return value ? value.split("/").pop() : "Thư viện"; };
  const pretty = (folder) => leaf(folder).replace(/-/g," ");
  const fileName = (file) => { if (file?.name) return String(file.name); try { return decodeURIComponent(String(file?.url||"").split("/").pop()||"file"); } catch (_) { return String(file?.url||"").split("/").pop()||"file"; } };
  const physical = () => allView() ? "" : active;
  async function post(url,payload) { const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:payload==null?null:JSON.stringify(payload)}); return {response,data:await response.json().catch(()=>({}))}; }
  function setProgress(percent,label) { const value=Math.max(0,Math.min(100,Math.round(Number(percent||0)))); el.progress.classList.add("show");el.progressBar.style.width=`${value}%`;el.progressText.textContent=`${value}%`;if(label)el.progressLabel.textContent=label; }
  function hideProgress(){setTimeout(()=>{el.progress.classList.remove("show");el.progressBar.style.width="0%";el.progressText.textContent="0%";el.progressLabel.textContent="Đang tải lên...";},700);}
  function selectedTotal(){return selectedFiles.size+selectedFolders.size;}
  function selectionLabel(){const parts=[];if(selectedFiles.size)parts.push(`${selectedFiles.size} file`);if(selectedFolders.size)parts.push(`${selectedFolders.size} folder`);return parts.join(" · ")||"0 mục";}
  function syncSelectionUi(){const total=selectedTotal();el.content.classList.toggle("is-selection-mode",selectionMode);el.selectionToolbar.hidden=total===0;el.selectionCount.textContent=`${selectionLabel()} đã chọn`;el.btnDeleteSelected.disabled=total===0;document.querySelectorAll(".selectable[data-select-kind]").forEach((node)=>{const kind=node.dataset.selectKind||"",id=kind==="folder"?String(node.dataset.folder||""):String(node.dataset.url||""),isSelected=kind==="folder"?selectedFolders.has(id):selectedFiles.has(id);node.classList.toggle("is-selected",isSelected);node.setAttribute("aria-selected",isSelected?"true":"false");const toggle=node.querySelector("[data-selection-toggle]");if(toggle){toggle.hidden=!selectionMode;toggle.tabIndex=selectionMode?0:-1;toggle.setAttribute("aria-pressed",isSelected?"true":"false");toggle.innerHTML=`<i class="fa-solid ${isSelected?"fa-check":"fa-plus"}"></i>`;}});}
  function clearSelection(sync=true,resetMode=true){selectedFiles.clear();selectedFolders.clear();if(resetMode)selectionMode=false;if(sync)syncSelectionUi();}
  function setSelection(kind,id,additive=false){const value=String(id||"");if(!value)return;if(!additive)clearSelection(false,false);const group=kind==="folder"?selectedFolders:selectedFiles;group.add(value);syncSelectionUi();}
  function toggleSelection(kind,id){const value=String(id||"");if(!value)return;const group=kind==="folder"?selectedFolders:selectedFiles;if(group.has(value))group.delete(value);else group.add(value);syncSelectionUi();}
  function setSelectionSets(nextFiles,nextFolders){selectedFiles=new Set(nextFiles);selectedFolders=new Set(nextFolders);syncSelectionUi();}
  function selectAllVisible(){selectionMode=true;setSelectionSets(visibleFiles().map((file)=>String(file.url||"")).filter(Boolean),directFolders().map((folder)=>String(folder||"")).filter(Boolean));}
  function select(folder, save=true) { const next=folder===ALL?ALL:norm(folder); if(next===active)return;clearSelection(false);active=next;if(save){history=history.slice(0,historyIndex+1);history.push(next);historyIndex=history.length-1;}el.title.textContent=allView()?"Tất cả folder":pretty(active);el.meta.textContent="Đang tải nội dung folder...";load(); }
  function directFolders(){const p=allView()?"":active,q=String(el.search.value||"").trim().toLocaleLowerCase("vi");return folders.filter((folder)=>parent(folder)===p&&(!q||pretty(folder).toLocaleLowerCase("vi").includes(q))).sort((a,b)=>a.localeCompare(b,"vi"));}
  function visibleFiles(){if(allView())return [];const q=String(el.search.value||"").trim().toLocaleLowerCase("vi"), type=el.type.value;let list=files.filter((file)=>String(file.folder||"")===active);if(type!=="all")list=list.filter((file)=>file.type===type);if(q)list=list.filter((file)=>`${fileName(file)} ${file.folder||""} ${file.url||""}`.toLocaleLowerCase("vi").includes(q));return list;}
  function renderTree(){const count=(folder)=>Math.max(0,Number(folderFileCounts[folder]||0));let html=`<button class="tree-item ${allView()?"active":""}" data-folder="${ALL}" type="button"><i class="fa-regular fa-folder-open"></i><span class="name">Tất cả folder</span><span class="count">${folders.length}</span></button>`;folders.slice().sort((a,b)=>a.localeCompare(b,"vi")).forEach((folder)=>{const depth=Math.max(0,norm(folder).split("/").length-1);html+=`<button class="tree-item ${active===folder?"active":""}" data-folder="${esc(folder)}" type="button" style="padding-left:${.6+depth*.8}rem"><i class="fa-solid fa-folder"></i><span class="name">${esc(pretty(folder))}</span><span class="count">${count(folder)}</span></button>`;});el.tree.innerHTML=html;}
  function renderCrumbs(){const chunks=allView()?[]:active.split("/");let html=`<button class="crumb ${chunks.length===0?"current":""}" type="button" data-folder="${ALL}"><i class="fa-regular fa-hard-drive me-1"></i>Thư viện</button>`, path="";chunks.forEach((chunk,index)=>{path+=(path?"/":"")+chunk;html+=`<span class="sep"><i class="fa-solid fa-chevron-right"></i></span><button class="crumb ${index===chunks.length-1?"current":""}" type="button" data-folder="${esc(path)}">${esc(pretty(chunk))}</button>`;});el.crumbs.innerHTML=html;}
  function renderFolders(){el.folders.innerHTML=directFolders().map((folder)=>{const directFiles=Math.max(0,Number(folderFileCounts[folder]||0)),children=folders.filter((candidate)=>parent(candidate)===folder).length,isSelected=selectedFolders.has(folder),toggleState=selectionMode?"":" hidden",toggleTabIndex=selectionMode?0:-1;return `<article class="folder-card selectable ${isSelected?"is-selected":""}" tabindex="0" role="button" aria-selected="${isSelected?"true":"false"}" data-folder="${esc(folder)}" data-select-kind="folder"><button class="selection-toggle" type="button" data-selection-toggle${toggleState} tabindex="${toggleTabIndex}" aria-label="Chọn folder ${esc(pretty(folder))}" aria-pressed="${isSelected?"true":"false"}"><i class="fa-solid ${isSelected?"fa-check":"fa-plus"}"></i></button><i class="fa-solid fa-folder"></i><span><strong>${esc(pretty(folder))}</strong><small>${directFiles} file${children?` · ${children} folder`:""}</small></span></article>`;}).join("");}
  function renderFiles(){const list=visibleFiles();el.grid.innerHTML=list.map((file)=>{const rawUrl=String(file.url||""),url=esc(rawUrl),name=esc(fileName(file)),type=file.type==="video"?"MP4":String(file.ext||"JPG").toUpperCase(),isSelected=selectedFiles.has(rawUrl),toggleState=selectionMode?"":" hidden",toggleTabIndex=selectionMode?0:-1,preview=file.type==="image"?`<img src="${url}" alt="" loading="lazy">`:`<span class="video-preview"><i class="fa-solid fa-film fa-2x"></i></span>`;return `<article class="media-card selectable ${isSelected?"is-selected":""}" tabindex="0" aria-selected="${isSelected?"true":"false"}" data-url="${url}" data-select-kind="file"><button class="selection-toggle" type="button" data-selection-toggle${toggleState} tabindex="${toggleTabIndex}" aria-label="Chọn file ${name}" aria-pressed="${isSelected?"true":"false"}"><i class="fa-solid ${isSelected?"fa-check":"fa-plus"}"></i></button><div class="media-preview">${preview}<span class="media-type">${esc(type)}</span></div><div class="media-info"><span class="media-name" title="${name}">${name}</span><span class="media-detail"><span>${bytes(file.size)}</span><span>${esc(date(file.mtime))}</span></span></div></article>`;}).join("");el.empty.classList.toggle("d-none",list.length!==0||directFolders().length!==0);}
  function render(){renderTree();renderCrumbs();renderFolders();renderFiles();el.btnBack.disabled=historyIndex<=0;el.btnUp.disabled=allView()||active==="";el.type.disabled=allView();el.title.textContent=allView()?"Tất cả folder":pretty(active);const shown=visibleFiles().length,rootFolders=directFolders().length;el.meta.textContent=allView()?`${rootFolders} folder cấp 1 · ${totalFiles} file trong thư viện · ảnh chỉ tải khi mở folder`:`${shown}${folderTotalFiles>shown?`/${folderTotalFiles}`:""} file trong folder này`;syncSelectionUi();}
  async function load(){const requestId=++loadSequence,requestedFolder=active,payload=allView()?{scope:"folders",root_folders_only:true}:{folder:active};el.meta.textContent="Đang tải nội dung folder...";const {response,data}=await post("/admin/api/media/list.php",payload);if(requestId!==loadSequence||requestedFolder!==active)return;if(!response.ok||!data.ok){window.adminToast("danger",data.message||"Không tải được thư viện.",{icon:"fa-solid fa-triangle-exclamation"});return;}files=Array.isArray(data.files)?data.files:[];folders=Array.from(new Set((Array.isArray(data.folders)?data.folders:[]).map(norm).filter(Boolean)));folderFileCounts=data.folder_file_counts&&typeof data.folder_file_counts==="object"&&!Array.isArray(data.folder_file_counts)?data.folder_file_counts:{};totalFiles=Number(data.total_files??files.length);folderTotalFiles=Number(data.folder_total_files??files.length);if(!allView()&&!folders.includes(active)){active=ALL;clearSelection(false);load();return;}clearSelection(false);render();}
  function showFolderDialog(folder=physical()){dialogParent=norm(folder);el.dialogPath.textContent=dialogParent?`Trong ${dialogParent}`:"Trong Thư viện";el.folderName.value="";if(typeof el.dialog.showModal==="function")el.dialog.showModal();else{const name=window.prompt(`Tạo folder trong ${dialogParent||"Thư viện"}:`);if(name)createFolder(name,dialogParent);}setTimeout(()=>el.folderName.focus(),0);}
  async function createFolder(name,parentFolder=dialogParent){const value=String(name||"").trim();if(!value)return;const {response,data}=await post("/admin/api/media/folder-create.php",{name:value,parent:norm(parentFolder)});if(!response.ok||!data.ok){window.adminToast("danger",data.message||"Không tạo được folder.",{icon:"fa-solid fa-triangle-exclamation"});return;}const folder=String(data.folder||"");window.adminToast("success",data.message||"Đã tạo folder.",{icon:"fa-solid fa-folder-plus"});await load();if(folder)select(folder);}
  async function copy(value){try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(value);return true;}}catch(_){}const area=document.createElement("textarea");area.value=value;area.style.cssText="position:fixed;left:-9999px";document.body.appendChild(area);area.select();const done=document.execCommand("copy");area.remove();return done;}
  async function upload(input){const queue=Array.from(input||[]).filter(Boolean);if(!queue.length)return;el.btnUpload.disabled=true;let uploaded=0,compressed=0,warnings=[];try{for(let i=0;i<queue.length;i+=1){const file=queue[i];setProgress(0,`Đang tải ${i+1}/${queue.length}: ${file.name}`);const {res,data}=await window.adminUploadFile(file,{folder:physical(),onProgress:(percent)=>setProgress(percent,percent>=100?`Đang xử lý và nén ${i+1}/${queue.length}: ${file.name}`:`Đang tải ${i+1}/${queue.length}: ${file.name}`)});if(!res.ok||!data.ok){window.adminToast("danger",`${file.name}: ${data.message||"Upload thất bại."}`,{icon:"fa-solid fa-triangle-exclamation"});continue;}uploaded+=1;const compression=data.file?.compression||{};if(compression.ok){compressed+=1;const oldSize=Number(compression.old_size||0),newSize=Number(compression.new_size||0);setProgress(100,`Đã nén ${i+1}/${queue.length}: ${file.name}${oldSize&&newSize?` (${bytes(oldSize)} → ${bytes(newSize)})`:""}`);}else{setProgress(100,`Đã tải ${i+1}/${queue.length}: ${file.name}`);}if(compression.warning)warnings.push(`${file.name}: ${compression.warning}`);}if(uploaded){window.adminToast("success",`Đã upload ${uploaded}/${queue.length} file${compressed?` · ${compressed} ảnh đã tự nén`:""}.`,{icon:"fa-solid fa-circle-check"});}if(warnings.length){window.adminToast("warning",warnings[0]+(warnings.length>1?` (+${warnings.length-1} ảnh khác)`:""),{icon:"fa-solid fa-triangle-exclamation"});}await load();}finally{el.btnUpload.disabled=false;hideProgress();}}
  async function compress(url){if(!window.confirm("Nén ảnh này thành JPG dưới 200 KB? Ảnh JPG sẽ bị ghi đè."))return;const {response,data}=await post("/admin/api/media/compress.php",{url});if(!response.ok||!data.ok){window.adminToast("danger",data.message||"Nén ảnh thất bại.",{icon:"fa-solid fa-triangle-exclamation"});return;}const file=data.file||{};window.adminToast("success",`Đã nén: ${bytes(file.old_size)} → ${bytes(file.new_size)}`,{icon:"fa-solid fa-circle-check"});if(file.url&&file.source_url&&file.url!==file.source_url){await copy(file.url);window.adminToast("info","Đã copy URL JPG mới.",{icon:"fa-solid fa-copy"});}await load();}
  async function remove(url){if(!window.confirm("Xoá file này? Hành động này không thể hoàn tác."))return;const {response,data}=await post("/admin/api/media/delete.php",{url});if(!response.ok||!data.ok){window.adminToast("danger",data.message||"Xoá file thất bại.",{icon:"fa-solid fa-triangle-exclamation"});return;}window.adminToast("success",data.message||"Đã xoá file.",{icon:"fa-solid fa-trash-can"});await load();}
  async function removeFolder(folder){const value=norm(folder);if(!value)return;const name=pretty(value);if(!window.confirm(`Xoá folder “${name}”?\n\nFolder trống sẽ được xoá ngay. Nếu còn nội dung, hệ thống sẽ hiển thị chi tiết để bạn xác nhận thêm một lần.`))return;let result=await post("/admin/api/media/folder-delete.php",{folder:value});if(!result.response.ok&&result.data?.code==="folder_not_empty"){const counts=result.data.counts||{},files=Number(counts.files||0),folders=Number(counts.folders||0),size=bytes(counts.bytes||0),typed=window.prompt(`Folder “${name}” có ${files} file, ${folders} folder con (${size}).\n\nẢnh đang được cơ sở, bác sĩ hoặc bài viết sử dụng có thể không hiển thị sau khi xoá.\n\nGõ XOA để xoá vĩnh viễn toàn bộ nội dung:`);if(String(typed||"").trim().toUpperCase()!=="XOA"){window.adminToast("info","Đã giữ nguyên folder và nội dung.",{icon:"fa-solid fa-folder"});return;}result=await post("/admin/api/media/folder-delete.php",{folder:value,recursive:true,confirmation:"DELETE_FOLDER_CONTENTS"});}const {response,data}=result;if(!response.ok||!data.ok){window.adminToast("danger",data.message||"Không xoá được folder.",{icon:"fa-solid fa-triangle-exclamation"});return;}const leavingDeletedFolder=active===value||active.startsWith(`${value}/`);window.adminToast("success",data.message||"Đã xoá folder.",{icon:"fa-solid fa-folder-minus"});if(leavingDeletedFolder){select(parent(value)||ALL);return;}await load();}
  function selectedItems(){return [...Array.from(selectedFiles).map((url)=>({kind:"file",url})),...Array.from(selectedFolders).map((folder)=>({kind:"folder",folder}))];}
  async function deleteSelected(){const items=selectedItems();if(!items.length)return;const preview=await post("/admin/api/media/bulk-delete.php",{items,preview:true});if(!preview.response.ok||!preview.data.ok){window.adminToast("danger",preview.data.message||"Không kiểm tra được các mục đã chọn.",{icon:"fa-solid fa-triangle-exclamation"});return;}const stats=preview.data.stats||{},fileCount=Number(stats.files||0),folderCount=Number(stats.folders||0),size=bytes(stats.bytes||0),selection=preview.data.selection||{},ignored=Number(selection.ignored_descendants||0),detail=`${fileCount} file, ${folderCount} folder (${size})`;if(!window.confirm(`Xoá vĩnh viễn ${detail}?\n\nẢnh đang được cơ sở, bác sĩ hoặc bài viết sử dụng có thể không hiển thị sau khi xoá.${ignored?`\n\n${ignored} mục con đã được gộp vào folder cha.`:""}`))return;const typed=window.prompt(`Gõ XOA để xác nhận xoá ${detail}:`);if(String(typed||"").trim().toUpperCase()!=="XOA"){window.adminToast("info","Đã giữ nguyên các mục đã chọn.",{icon:"fa-solid fa-folder"});return;}const result=await post("/admin/api/media/bulk-delete.php",{items,confirmation:"DELETE_SELECTED_ITEMS"});if(!result.response.ok||!result.data.ok){window.adminToast("danger",result.data.message||"Xoá hàng loạt chưa hoàn tất. Thư viện sẽ được tải lại để kiểm tra.",{icon:"fa-solid fa-triangle-exclamation"});clearSelection(false);await load();return;}const deleted=result.data.deleted||{};window.adminToast("success",`Đã xoá ${Number(deleted.files||0)} file và ${Number(deleted.folders||0)} folder.`,{icon:"fa-solid fa-trash-can"});clearSelection(false);await load();}
  function hideMenu(){el.menu.hidden=true;contextTarget=null;}
  function menu(event,target){event.preventDefault();contextTarget=target;const hasMultiple=selectedTotal()>1,bulkAction=hasMultiple?[["sep"],["delete-selected","fa-trash-can",`Xoá ${selectionLabel()} đã chọn`,"danger"]]:[],actions=target.kind==="file"?[["preview","fa-arrow-up-right-from-square",target.file.type==="image"?"Xem ảnh":"Mở file"],["copy","fa-copy","Copy URL"],...(target.file.type==="image"?[["compress","fa-compress","Nén ảnh (<200 KB)"]]:[]),["sep"],["delete","fa-trash-can","Xoá file","danger"],...bulkAction]:[["open","fa-folder-open",target.folder===ALL?"Mở tất cả file":"Mở folder"],["new","fa-folder-plus","Tạo folder mới tại đây"],["copy-folder","fa-copy","Copy đường dẫn folder"],...(target.folder===ALL?[]:[["sep"],["delete-folder","fa-folder-minus","Xoá folder…","danger"]]),...bulkAction];el.menu.innerHTML=actions.map((action)=>action[0]==="sep"?'<div class="context-sep"></div>':`<button class="context-action ${action[3]||""}" type="button" data-action="${action[0]}"><i class="fa-solid ${action[1]}"></i>${action[2]}</button>`).join("");el.menu.hidden=false;el.menu.style.left=`${Math.max(8,Math.min(event.clientX,window.innerWidth-el.menu.offsetWidth-10))}px`;el.menu.style.top=`${Math.max(8,Math.min(event.clientY,window.innerHeight-el.menu.offsetHeight-10))}px`;}
  function cardData(card){if(!card)return null;const kind=String(card.dataset.selectKind||"");const id=kind==="folder"?String(card.dataset.folder||""):String(card.dataset.url||"");return (kind==="folder"||kind==="file")&&id?{kind,id}:null;}
  function toggleCard(card){const data=cardData(card);if(data)toggleSelection(data.kind,data.id);}
  function selectCard(card){const data=cardData(card);if(!data)return;selectionMode=true;toggleSelection(data.kind,data.id);}
  function openCard(card){const data=cardData(card);if(!data)return;if(data.kind==="folder")select(data.id);else window.open(data.id,"_blank","noopener");}
  function isTextEntry(node){return !!node?.closest?.("input,textarea,select,[contenteditable='true']");}
  function updateLasso(event){if(!lasso||event.pointerId!==lasso.pointerId)return;const x=Math.min(lasso.startX,event.clientX),y=Math.min(lasso.startY,event.clientY),width=Math.abs(event.clientX-lasso.startX),height=Math.abs(event.clientY-lasso.startY);if(!lasso.moved&&width<5&&height<5)return;lasso.moved=true;el.marquee.hidden=false;el.marquee.style.left=`${x}px`;el.marquee.style.top=`${y}px`;el.marquee.style.width=`${width}px`;el.marquee.style.height=`${height}px`;const nextFiles=lasso.additive?new Set(lasso.baseFiles):new Set(),nextFolders=lasso.additive?new Set(lasso.baseFolders):new Set(),right=x+width,bottom=y+height;document.querySelectorAll(".selectable[data-select-kind]").forEach((card)=>{const rect=card.getBoundingClientRect();if(rect.right>=x&&rect.left<=right&&rect.bottom>=y&&rect.top<=bottom){const data=cardData(card);if(!data)return;if(data.kind==="folder")nextFolders.add(data.id);else nextFiles.add(data.id);}});setSelectionSets(nextFiles,nextFolders);}
  function endLasso(event){if(!lasso||event.pointerId!==lasso.pointerId)return;const moved=lasso.moved;try{if(el.content.hasPointerCapture?.(event.pointerId))el.content.releasePointerCapture(event.pointerId);}catch(_){}lasso=null;el.marquee.hidden=true;el.content.classList.remove("is-selecting");if(moved){suppressCardClick=true;setTimeout(()=>{suppressCardClick=false;},0);}}
  function startLasso(event){if(event.pointerType==="touch"||event.button!==0||event.target.closest(".selectable,button,input,textarea,select,a,label")||!event.target.closest("#folderGrid,#mediaGrid"))return;selectionMode=true;if(!(event.metaKey||event.ctrlKey))clearSelection(false,false);syncSelectionUi();lasso={pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,baseFiles:new Set(selectedFiles),baseFolders:new Set(selectedFolders),additive:Boolean(event.metaKey||event.ctrlKey),moved:false};try{el.content.setPointerCapture(event.pointerId);}catch(_){}el.content.classList.add("is-selecting");}
  function bindCardGrid(container){container.addEventListener("click",(event)=>{if(suppressCardClick)return;const card=event.target.closest(".selectable[data-select-kind]");if(!card||!container.contains(card))return;if(event.target.closest("[data-selection-toggle]")){event.preventDefault();event.stopPropagation();selectionMode=true;toggleCard(card);return;}if(event.metaKey||event.ctrlKey){event.preventDefault();selectCard(card);return;}openCard(card);});container.addEventListener("keydown",(event)=>{const card=event.target.closest(".selectable[data-select-kind]");if(!card||!container.contains(card))return;if(event.key===" "){event.preventDefault();selectionMode=true;toggleCard(card);return;}if(event.key==="Enter"){event.preventDefault();openCard(card);}});}
  bindCardGrid(el.folders);bindCardGrid(el.grid);
  el.tree.addEventListener("click",(event)=>{const button=event.target.closest("[data-folder]");if(button)select(button.dataset.folder||ALL);});el.crumbs.addEventListener("click",(event)=>{const button=event.target.closest("[data-folder]");if(button)select(button.dataset.folder||ALL);});
  document.addEventListener("contextmenu",(event)=>{const selectable=event.target.closest(".selectable[data-select-kind]");if(selectable){const data=cardData(selectable);if(data){const group=data.kind==="folder"?selectedFolders:selectedFiles;if(!group.has(data.id))setSelection(data.kind,data.id);if(data.kind==="file"){const file=files.find((item)=>String(item.url||"")===data.id);if(file)menu(event,{kind:"file",file});return;}menu(event,{kind:"folder",folder:data.id});return;}}const folder=event.target.closest("[data-folder]");if(folder&&(folder.closest("#folderTree")||folder.closest("#folderGrid"))){menu(event,{kind:"folder",folder:folder.dataset.folder||ALL});return;}if(event.target.closest("#finderContent")||event.target.closest("#finderSide"))menu(event,{kind:"folder",folder:physical()||ALL});});document.addEventListener("click",(event)=>{if(!el.menu.hidden&&!event.target.closest("#contextMenu"))hideMenu();});document.addEventListener("keydown",(event)=>{if(event.key==="Escape"){if(selectedTotal())clearSelection();hideMenu();return;}if(isTextEntry(event.target))return;const isMeta=event.metaKey||event.ctrlKey;if(isMeta&&event.key.toLowerCase()==="a"){event.preventDefault();selectAllVisible();return;}if((event.key==="Delete"||event.key==="Backspace")&&selectedTotal()){event.preventDefault();deleteSelected();}});
  el.menu.addEventListener("click",async(event)=>{const action=event.target.closest("[data-action]")?.dataset.action,target=contextTarget;hideMenu();if(!action||!target)return;if(action==="delete-selected"){await deleteSelected();return;}if(target.kind==="folder"){if(action==="open")select(target.folder||ALL);if(action==="new")showFolderDialog(target.folder===ALL?"":target.folder);if(action==="copy-folder"&&await copy(target.folder===ALL?"/uploads/library":`/uploads/library/${target.folder}`))window.adminToast("success","Đã copy đường dẫn folder.",{icon:"fa-solid fa-copy"});if(action==="delete-folder")await removeFolder(target.folder);return;}if(action==="preview")window.open(target.file.url,"_blank","noopener");if(action==="copy"&&await copy(target.file.url))window.adminToast("success","Đã copy URL file.",{icon:"fa-solid fa-copy"});if(action==="compress")await compress(target.file.url);if(action==="delete")await remove(target.file.url);});
  el.btnUpload.addEventListener("click",()=>el.uploadInput.click());el.btnNewFolder.addEventListener("click",()=>showFolderDialog());el.btnReload.addEventListener("click",load);el.btnBack.addEventListener("click",()=>{if(historyIndex>0){historyIndex-=1;select(history[historyIndex],false);}});el.btnUp.addEventListener("click",()=>{if(!allView())select(parent(active)||ALL);});el.type.addEventListener("change",()=>{clearSelection(false);render();});el.search.addEventListener("input",()=>{clearSelection(false);render();});el.btnSelectAll.addEventListener("click",selectAllVisible);el.btnSelectAllQuick.addEventListener("click",selectAllVisible);el.btnClearSelection.addEventListener("click",()=>clearSelection());el.btnDeleteSelected.addEventListener("click",deleteSelected);el.content.addEventListener("pointerdown",startLasso);el.content.addEventListener("pointermove",updateLasso);el.content.addEventListener("pointerup",endLasso);el.content.addEventListener("pointercancel",endLasso);el.uploadInput.addEventListener("change",async()=>{const input=el.uploadInput.files;el.uploadInput.value="";await upload(input);});el.content.addEventListener("dragover",(event)=>{event.preventDefault();el.content.classList.add("dragging");});el.content.addEventListener("dragleave",(event)=>{if(!el.content.contains(event.relatedTarget))el.content.classList.remove("dragging");});el.content.addEventListener("drop",async(event)=>{event.preventDefault();el.content.classList.remove("dragging");await upload(event.dataTransfer?.files);});el.form.addEventListener("submit",async(event)=>{event.preventDefault();const name=el.folderName.value;if(typeof el.dialog.close==="function")el.dialog.close();await createFolder(name,dialogParent);});el.cancelFolder.addEventListener("click",()=>el.dialog.close());
  load();
</script>

<?php require __DIR__ . '/_layout_end.php'; ?>
